Repository jamiejpace/viewing_party, pull requests merged in 2021-10, with the labels that each got.

#23 Pr template
  Gemfile
  Gemfile.lock
  docs/pull_request_template.md
  spec/rails_helper.rb
Labels: chore

#30 Registration
  Gemfile
  Gemfile.lock
  app/controllers/users_controller.rb
  app/models/user.rb
  app/views/users/new.html.erb
  app/views/welcome/index.html.erb
  config/routes.rb
  spec/features/users/registration_spec.rb
  spec/features/welcome/index_spec.rb
Labels: Core

#34 Finalize testing for movie index page
  app/controllers/movies_controller.rb
  app/views/movies/index.html.erb
  spec/features/movies/index_spec.rb
  spec/fixtures/vcr_cassettes/movies_index_page/displays_an_error_message_when_no_movies_are_found.yml
  spec/fixtures/vcr_cassettes/movies_index_page/displays_an_error_message_when_nothing_is_entered_into_the_field.yml
Labels: Core, API consumption

#35 Movie display page
  app/controllers/movies_controller.rb
  app/facades/movie_facade.rb
  app/poros/cast.rb
  app/poros/movie.rb
  app/poros/review.rb
  app/services/movie_service.rb
  app/views/movies/index.html.erb
  app/views/movies/show.html.erb
  config/routes.rb
  spec/facades/movie_facade_spec.rb
  spec/features/movies/index_spec.rb
  spec/features/movies/show_spec.rb
  spec/fixtures/vcr_cassettes/movie_facade/can_return_a_cast_of_a_movie_that_matches_the_given_id.yml
  spec/fixtures/vcr_cassettes/movie_facade/can_return_a_movie_that_matches_the_given_id.yml
  spec/fixtures/vcr_cassettes/movie_facade/can_return_reviews_of_a_movie_that_matches_the_given_id.yml
  spec/fixtures/vcr_cassettes/movie_service/gets_a_custom_search_based_on_a_search_param.yml
  spec/fixtures/vcr_cassettes/movie_service/gets_the_cast_of_a_given_movie.yml
  spec/fixtures/vcr_cassettes/movie_service/gets_the_details_of_a_movie_given_the_id_of_that_movie.yml
  spec/fixtures/vcr_cassettes/movie_service/gets_the_reviews_for_a_given_movie.yml
  spec/fixtures/vcr_cassettes/movie_service/gets_the_top_20_movies.yml
  spec/fixtures/vcr_cassettes/movies_show_page/displays_movie_details.yml
  spec/fixtures/vcr_cassettes/movies_show_page/links_to_movie_show_page_from_the_index_page.yml
  spec/poros/cast_spec.rb
  spec/poros/movie_spec.rb
  spec/poros/review_spec.rb
  spec/services/movie_service_spec.rb
Labels: Core, API consumption

#36 Update migration file to include enum for attendees
  app/models/attendee.rb
  app/views/users/show.html.erb
  db/migrate/20211012202557_create_parties.rb
  db/migrate/20211012202731_create_attendees.rb
  db/schema.rb
  spec/features/users/dashboard_spec.rb
Labels: Core

#40 Refactor 1
  app/assets/stylesheets/application.scss
  app/channels/application_cable/channel.rb
  app/channels/application_cable/connection.rb
  app/controllers/parties_controller.rb
  app/controllers/sessions_controller.rb
  app/facades/movie_facade.rb
  app/jobs/application_job.rb
  app/mailers/application_mailer.rb
  app/models/application_record.rb
  app/models/attendee.rb
  app/models/user.rb
  app/views/layouts/application.html.erb
  app/views/movies/index.html.erb
  app/views/movies/show.html.erb
  app/views/welcome/index.html.erb
  config/routes.rb
  spec/features/movies/index_spec.rb
  spec/features/movies/show_spec.rb
  spec/features/parties/new_spec.rb
  spec/features/users/dashboard_spec.rb
  spec/features/users/registration_spec.rb
  spec/features/welcome/index_spec.rb
  spec/fixtures/vcr_cassettes/movies_show_page/can_redirect_to_the_create_a_new_party_page.yml
  spec/fixtures/vcr_cassettes/new_party_page/can_create_a_new_party_provided_party_information.yml
  spec/fixtures/vcr_cassettes/new_party_page/can_display_an_error_if_valid_information_is_not_provided_and/or_friends_are_not_invited.yml
  spec/fixtures/vcr_cassettes/new_party_page/displays_the_movie_title_and_all_form_information.yml
Labels: exploration
